package com.akshaj.quizservice.model;

import lombok.Data;

import javax.persistence.*;
import java.util.List;

@Data
@Entity
public class Quiz {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @GeneratedValue(strategy = GenerationType.IDENTITY) annotation specifies that the primary key values should be generated by the database using the identity strategy.
//    By using GenerationType.IDENTITY, you don't need to manually assign values to the primary key field when inserting new records.
//    The database will take care of generating and assigning the unique values automatically.
    private Integer Id;
    private String title;


//    when we are using numbers or specific type which is only one we will use element questions
    @ElementCollection
    private List<Integer> questionIds;
}
